language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t ahmoud2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahmoud2/react-test npm test

after_success:
  - docker build -t ahmoud2/multi-client ./client
  - docker build -t ahmoud2/multi-nginx ./nginx
  - docker build -t ahmoud2/multi-server ./server
  - docker build -t ahmoud2/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push ahmoud2/multi-client
  - docker push ahmoud2/multi-nginx
  - docker push ahmoud2/multi-server
  - docker push ahmoud2/multi-worker